In [1]:
import tensorflow as tf 
tf.reset_default_graph()

# constant 를 선언해 보세요. (3.0 과 4.0)
a = tf.constant(3.0)
b = tf.constant(4.0)
total = a + b
print(a)
print(b)
print(total)

sess = tf.Session()
print(sess.run(total))
print(sess.run([a, b]))

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)
7.0
[3.0, 4.0]


In [2]:
import tensorflow as tf 
tf.reset_default_graph()

# constant 를 선언해 보세요. (3.0 과 4.0)
a = tf.constant([3.0,4.0])
print(a)

sess = tf.Session()
print(sess.run(a))

Tensor("Const:0", shape=(2,), dtype=float32)
[3. 4.]


## placeholder

In [8]:
import tensorflow as tf 
tf.reset_default_graph()

# placeholder 를 선언해보세요.
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y
print(x)
print(y)
print(z)

sess = tf.Session()
# sess run 을 실행해 보세요. x = 3, y = 4.5
result = sess.run(z, feed_dict={x:3, y:4.5})
print(result)

Tensor("Placeholder:0", dtype=float32)
Tensor("Placeholder_1:0", dtype=float32)
Tensor("add:0", dtype=float32)
7.5


In [9]:
# with shape
import tensorflow as tf 
tf.reset_default_graph()

# placeholder 를 선언해보세요. (shape 에 유의)
x1 = tf.placeholder(tf.float32, shape=[2])
y1 = tf.placeholder(tf.float32, shape=[2])
z1 = x1 + y1
print(x1)
print(y1)
print(z1)

sess = tf.Session()
# sess run 을 실행해 보세요. x1 = (1, 3), y1 = (2, 4)
result = sess.run(z1, feed_dict={x1:[1,3], y1:[2,4]})
print(result)

Tensor("Placeholder:0", shape=(2,), dtype=float32)
Tensor("Placeholder_1:0", shape=(2,), dtype=float32)
Tensor("add:0", shape=(2,), dtype=float32)
[3. 7.]


## variable

In [12]:
import tensorflow as tf 
tf.reset_default_graph()

# variable 을 선언해 보세요. (이름은 아래에서 찾아보세요.)
my_variable = tf.get_variable("my_variable", [1,2,3])
# int 32, zero initializer
my_int_variable = tf.get_variable("my_int_variable", [1,2,3], dtype=tf.int32, initializer=tf.zeros_initializer)

print(my_variable)
print(my_int_variable)

sess = tf.Session()
# initialzier 실행

# sess run 실행
sess.run(tf.global_variables_initializer()) 
my, my_init = sess.run([my_variable, my_int_variable])
print(my)
print(my_init)

<tf.Variable 'my_variable:0' shape=(1, 2, 3) dtype=float32_ref>
<tf.Variable 'my_int_variable:0' shape=(1, 2, 3) dtype=int32_ref>
[[[-0.27024144 -0.67154694  0.52835596]
  [ 0.05975068 -0.7674236   0.78690743]]]
[[[0 0 0]
  [0 0 0]]]


## 에러상황

In [11]:
# error case
import tensorflow as tf 
tf.reset_default_graph()

my_variable = tf.get_variable("my_variable", [1]) 
try:
    dup = tf.get_variable("my_variable", [1]) 
except ValueError:
    print("ValueError")

ValueError


### 1. reset 하기

In [17]:
import tensorflow as tf 
# reset 해 보세요.

tf.reset_default_graph()
my_variable = tf.get_variable("my_variable", [1]) 
tf.reset_default_graph()
dup = tf.get_variable("my_variable", [1]) 
print(my_variable)
print(dup)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer()) 
    try:
        print(sess.run(my_variable))
    except ValueError:
        print("ValueError")
    print(sess.run(dup))

<tf.Variable 'my_variable:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'my_variable:0' shape=(1,) dtype=float32_ref>
ValueError
[-0.20567131]


### variable scope

In [23]:
import tensorflow as tf 
# variable scope 를 선언해 보세요. (이름은 아래를 참조하세요.)
tf.reset_default_graph()
with tf.variable_scope('foo'):
    my_variable = tf.get_variable("my_variable", [1]) 
with tf.variable_scope('bar'):
    dup = tf.get_variable("my_variable", [1])
    
print(my_variable)
print(dup)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer()) 
    print(sess.run(my_variable))
    print(sess.run(dup))

<tf.Variable 'foo/my_variable:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'bar/my_variable:0' shape=(1,) dtype=float32_ref>
[-1.68381]
[-1.5890906]


In [27]:
import tensorflow as tf 
tf.reset_default_graph()

# variable scope 와 reuse 를 선언해 보세요. (이름은 아래를 참조하세요.)
with tf.variable_scope('foo'):
    my_variable = tf.get_variable("my_variable", [1]) 
with tf.variable_scope('foo', reuse=True):
    dup = tf.get_variable("my_variable", [1])

print(my_variable)
print(dup)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer()) 
    print(sess.run(my_variable))
    print(sess.run(dup))

<tf.Variable 'foo/my_variable:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'foo/my_variable:0' shape=(1,) dtype=float32_ref>
[1.0756522]
[1.0756522]


### initializer

In [15]:
import tensorflow as tf 
tf.reset_default_graph()

v = tf.get_variable("v", [1, 2, 3], dtype=tf.float32)
sess = tf.Session()
sess.run(tf.global_variables_initializer()) 
print(sess.run(v))

[[[ 0.38497305 -0.5529714   0.40448713]
  [ 0.95871353  0.8886858   0.88998544]]]


In [28]:
import tensorflow as tf 
tf.reset_default_graph()

# zero initializer
v1 = tf.get_variable('v1',[1,2,3], dtype=tf.float32, initializer = tf.zeros_initializer)
# constant initializer
v2 = tf.get_variable('v2',[1,2,3], dtype=tf.float32, initializer= tf.constant_initializer(1.0))

sess = tf.Session()
sess.run(tf.global_vanormalriables_initializer()) 
o1, o2 = sess.run([v1, v2]) 

print(o1)
print(o2)

[[[0. 0. 0.]
  [0. 0. 0.]]]
[[[1. 1. 1.]
  [1. 1. 1.]]]


In [29]:
import tensorflow as tf 
tf.reset_default_graph()

# 정규 분포 initializer
v3 = tf.get_variable('v3', [1,2,3], dtype=tf.float32, initializer=tf.random_normal_initializer())
# uniform 분포 initializer
v4 = tf.get_variable('v4', [1,2,3], dtype=tf.float32, initializer=tf.random_uniform_initializer())
sess = tf.Session()
sess.run(tf.global_variables_initializer()) 
o3, o4 = sess.run([v3, v4]) 

print(o3)
print(o4)

[[[ 1.0836632  -0.13845229 -0.9691878 ]
  [-0.89696795  0.7812816   1.4676005 ]]]
[[[0.33334744 0.06550038 0.61315   ]
  [0.5348885  0.8134992  0.7971686 ]]]


# Examples

In [30]:
import tensorflow as tf 
tf.reset_default_graph()

x = tf.placeholder(tf.float32)
w = tf.get_variable("w", 
            initializer=tf.constant([2.]))
b = tf.constant(4.0) 
y= x*w + b

print(x)
print(w) 
print(b) 
print(y)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(y, feed_dict={x: 1}))

Tensor("Placeholder:0", dtype=float32)
<tf.Variable 'w:0' shape=(1,) dtype=float32_ref>
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", dtype=float32)
[6.]


In [31]:
import tensorflow as tf 
tf.reset_default_graph()

x = tf.placeholder(tf.float32, shape=[1])
w = tf.get_variable("w", shape=[1], 
        initializer=tf.zeros_initializer)
b = tf.constant([4.0])
y= x*w + b

print(x)
print(w) 
print(b) 
print(y)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(y, feed_dict={x: [1]}))

Tensor("Placeholder:0", shape=(1,), dtype=float32)
<tf.Variable 'w:0' shape=(1,) dtype=float32_ref>
Tensor("Const:0", shape=(1,), dtype=float32)
Tensor("add:0", shape=(1,), dtype=float32)
[4.]


In [32]:
import numpy as np
import tensorflow as tf 
tf.reset_default_graph()

x = tf.placeholder(tf.float32, shape=[None, 2])
w = tf.get_variable("w", shape=[2],
        initializer=tf.random_normal_initializer())
y= x*w

print(x)
print(w) 
print(y)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(y, feed_dict={x: np.random.rand(3, 2)}))

Tensor("Placeholder:0", shape=(?, 2), dtype=float32)
<tf.Variable 'w:0' shape=(2,) dtype=float32_ref>
Tensor("mul:0", shape=(?, 2), dtype=float32)
[[-0.6400163  -0.20591749]
 [-0.31755203 -1.1063311 ]
 [-0.6997827  -1.312068  ]]


# Using GPUs

In [21]:
import tensorflow as tf 

with tf.device("/device:GPU:0"):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
    
c = tf.matmul(a, b)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
# Runs the op.
print(sess.run(c))

[[22. 28.]
 [49. 64.]]
